[build]
  publish = "."
  command = ""  # No build command needed for static HTML 

[edge_functions]
  directory = "netlify/edge-functions"



# Blog category redirects - redirect to main blog page
[[redirects]]
  from = "/blog?category=*"
  to = "/blog/"
  status = 301

## Removed specific category redirects in favor of generic query matching above

# Query-param aware redirects (Netlify TOML syntax)
[[redirects]]
  from = "/blog"
  to = "/blog/"
  status = 301
  query = { category = ":category" }

[[redirects]]
  from = "/blog/"
  to = "/blog/"
  status = 301
  query = { category = ":category" }

# Blog post trailing slash redirects
[[redirects]]
  from = "/blog"
  to = "/blog/"
  status = 301

[[redirects]]
  from = "/blog/:slug"
  to = "/blog/:slug/"
  status = 301
## Removed specific slug trailing-slash redirects; covered by /blog/:slug rule



# Redirect legacy /form to /quote
[[redirects]]
  from = "/form"
  to = "/quote/"
  status = 301

[[redirects]]
  from = "/form/"
  to = "/quote/"
  status = 301

# Canonicalize host: redirect www -> apex
[[redirects]]
  from = "/:splat"
  to = "https://grimetodime.com/:splat"
  status = 301
  force = true
  conditions = { Host = "www.grimetodime.com" }

# Ensure HTTP -> HTTPS (single hop)
[[redirects]]
  from = "http://grimetodime.com/:splat"
  to = "https://grimetodime.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.grimetodime.com/:splat"
  to = "https://grimetodime.com/:splat"
  status = 301
  force = true

# Catch blog tag querystrings to canonical URL
[[redirects]]
  from = "/blog?tag=*"
  to = "/blog/"
  status = 301

[[redirects]]
  from = "/blog/?tag=*"
  to = "/blog/"
  status = 301

[[edge_functions]]
  path = "/blog"
  function = "strip-blog-query"

[[edge_functions]]
  path = "/blog/"
  function = "strip-blog-query"

[[edge_functions]]
  path = "/blog/*"
  function = "strip-blog-query"

[[redirects]]
  from = "/blog"
  to = "/blog/"
  status = 301
  query = { tag = ":tag" }

[[redirects]]
  from = "/blog/"
  to = "/blog/"
  status = 301
  query = { tag = ":tag" }
