[build]
  publish = "."
  command = ""  # No build command needed for static HTML 

[[redirects]]
  from = "/unsubscribe"
  to = "/unsubscribe/"
  status = 301

[[redirects]]
  from = "/unsubscribed"
  to = "/unsubscribed/"
  status = 301

# Blog category redirects - redirect to main blog page
[[redirects]]
  from = "/blog?category=*"
  to = "/blog/"
  status = 302

# Specific category URL redirects (catch remaining GSC detected URLs)
[[redirects]]
  from = "/blog/?category=recycling"
  to = "/blog/"
  status = 302

[[redirects]]
  from = "/blog/?category=diy"
  to = "/blog/"
  status = 302

[[redirects]]
  from = "/blog?category=recycling"
  to = "/blog/"
  status = 302

[[redirects]]
  from = "/blog?category=diy"
  to = "/blog/"
  status = 302

# Additional specific category URL redirects (new GSC detected URLs)
[[redirects]]
  from = "/blog/?category=sustainability"
  to = "/blog/"
  status = 302

[[redirects]]
  from = "/blog/?category=organization"
  to = "/blog/"
  status = 302

[[redirects]]
  from = "/blog/?category=cleaning"
  to = "/blog/"
  status = 302

[[redirects]]
  from = "/blog?category=sustainability"
  to = "/blog/"
  status = 302

[[redirects]]
  from = "/blog?category=organization"
  to = "/blog/"
  status = 302

[[redirects]]
  from = "/blog?category=cleaning"
  to = "/blog/"
  status = 302

# Blog post trailing slash redirects
[[redirects]]
  from = "/blog/10-items-you-didnt-know-could-be-recycled"
  to = "/blog/10-items-you-didnt-know-could-be-recycled/"
  status = 301

[[redirects]]
  from = "/blog/upcycling-guide"
  to = "/blog/upcycling-guide/"
  status = 301

[[redirects]]
  from = "/blog/winter-organization-tips"
  to = "/blog/winter-organization-tips/"
  status = 301

[[redirects]]
  from = "/blog/end-of-summer-deep-clean"
  to = "/blog/end-of-summer-deep-clean/"
  status = 301

# Form redirect - ensure proper handling
[[redirects]]
  from = "/form"
  to = "/quote/"
  status = 302